[[new-features]]
= New & Noteworthy

[[new-features.5-3-0]]
== What's new in Lettuce 5.3

* Improved SSL configuration supporting Cipher suite selection and PEM-encoded certificates.
* Fixed method signature for `randomkey()`.
* Un-deprecated `ClientOptions.pingBeforeActivateConnection` to allow connection verification during connection handshake.

[[new-features.5-2-0]]
== What's new in Lettuce 5.2

* Allow randomization of read candidates using Redis Cluster.
* SSL support for Redis Sentinel.

[[new-features.5-1-0]]
== What's new in Lettuce 5.1

* Add support for `ZPOPMIN`, `ZPOPMAX`, `BZPOPMIN`, `BZPOPMAX` commands.
* Add support for Redis Command Tracing through Brave, see <<client-resources>>.
* Add support for https://redis.io/topics/streams-intro[Redis Streams].
* Asynchronous `connect()` for Master/Replica connections.
* <<connection-pooling.asynchronous.usage>> through `AsyncConnectionPoolSupport` and `AsyncPool`.
* Dedicated exceptions for Redis `LOADING`, `BUSY`, and `NOSCRIPT` responses.
* Commands in at-most-once mode (auto-reconnect disabled) are now canceled already on disconnect.
* Global command timeouts (also for reactive and asynchronous API usage) configurable through <<client-options>>.
* Host and port mappers for Lettuce usage behind connection tunnels/proxies through `SocketAddressResolver`, see <<client-resources>>.
* `SCRIPT LOAD` dispatch to all cluster nodes when issued through `RedisAdvancedClusterCommands`.
* Reactive `ScanStream` to iterate over the keyspace using `SCAN` commands.
* Transactions using Master/Replica connections are bound to the master node.

[[new-features.5-0-0]]
== What's new in Lettuce 5.0

* New artifact coordinates: `io.lettuce:lettuce-core` and packages moved from `com.lambdaworks.redis` to `io.lettuce.core`.
* <<reactive-api,Reactive API>> now Reactive Streams-based using https://projectreactor.io/[Project Reactor].
* <<redis-command-interfaces,Redis Command Interfaces>> supporting dynamic command invocation and Redis Modules.
* Enhanced, immutable Key-Value objects.
* Asynchronous Cluster connect.
* Native transport support for Kqueue on macOS systems.
* Removal of support for Guava.
* Removal of deprecated `RedisConnection` and `RedisAsyncConnection` interfaces.
* Java 9 compatibility.
* HTML and PDF reference documentation along with a new project website: https://lettuce.io.
