/*
 * Copyright 2025, Redis Ltd. and Contributors
 * All rights reserved.
 *
 * Licensed under the MIT License.
 */

package io.lettuce.core.api.coroutines

import io.lettuce.core.ExperimentalLettuceCoroutinesApi
import kotlinx.coroutines.flow.Flow
import io.lettuce.core.search.Field
import io.lettuce.core.search.arguments.CreateArgs

/**
 * Coroutine executed commands for RediSearch functionality
 *
 * @param <K> Key type.
 * @param <V> Value type.
 * @author Tihomir Mateev
 * @see <a href="https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/search/">RediSearch</a>
 * @since 6.6
 * @generated by io.lettuce.apigenerator.CreateKotlinCoroutinesApi
 */
@ExperimentalLettuceCoroutinesApi
interface RediSearchCoroutinesCommands<K : Any, V : Any> {

    /**
     * Create a new index with the given name, index options, and fields.
     *
     * @param index the index name, as a key
     * @param options the index [CreateArgs]
     * @param fields the [Field]s of the index
     * @return the result of the create command
     * @since 6.6
     * @see <a href="https://redis.io/docs/latest/commands/ft.create/">FT.CREATE</a>
     */
    suspend fun ftCreate(index: K, options: CreateArgs<K, V>, fields: List<Field<K>>): String?

    /**
     * Drop an index.
     * <p/>
     * By default, <a href="https://redis.io/docs/latest/commands/ft.dropindex/">FT.DROPINDEX</a> does not delete the documents
     * associated with the index. Adding the <code>deleteDocuments</code> option deletes the documents as well. If an index
     * creation is still running (<a href="https://redis.io/docs/latest/commands/ft.create/">FT.CREATE</a> is running
     * asynchronously), only the document hashes that have already been indexed are deleted. The document hashes left to be
     * indexed remain in the database.
     *
     * @param index the index name, as a key
     * @param deleteDocuments if true, delete the documents as well
     * @return the result of the drop command
     * @since 6.6
     * @see <a href="https://redis.io/docs/latest/commands/ft.dropindex/">FT.DROPINDEX</a>
     */
    suspend fun ftDropindex(index: K, deleteDocuments: Boolean): String?

}

