package io.lettuce.core.api.reactive;

import io.lettuce.core.bf.BfInfoValue;
import io.lettuce.core.bf.BfScanDumpValue;
import io.lettuce.core.bf.arguments.BfInsertArgs;
import io.lettuce.core.bf.arguments.BfReserveArgs;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Reactive executed commands for Bloom Filter.
 *
 * @author Yordan Tsintsov
 * @param <K> Key type.
 * @param <V> Value type.
 * @see <a href="https://redis.io/docs/latest/develop/data-types/probabilistic/bloom-filter/">Redis Bloom Filter</a>
 * @since 7.6
 * @generated by io.lettuce.apigenerator.CreateReactiveApi
 */
public interface RedisBloomFilterReactiveCommands<K, V> {

    /**
     * Add an item to the Bloom Filter.
     *
     * @param key the key.
     * @param value the value.
     * @return Boolean integer-reply {@code true} if the item was added, {@code false} if it was already in the filter.
     */
    Mono<Boolean> bfAdd(K key, V value);

    /**
     * Get the number of items added and detected as unique in the Bloom Filter.
     *
     * @param key the key.
     * @return Long integer-reply the number of items in the filter.
     */
    Mono<Long> bfCard(K key);

    /**
     * Check if an item exists in the Bloom Filter.
     *
     * @param key the key.
     * @param value the value.
     * @return Boolean integer-reply {@code true} if the item may exist in the filter, {@code false} if it definitely does not.
     */
    Mono<Boolean> bfExists(K key, V value);

    /**
     * Get information about the Bloom Filter.
     *
     * @param key the key.
     * @return BfInfoValue the information about the filter.
     */
    Mono<BfInfoValue> bfInfo(K key);

    /**
     * Add an item to the Bloom Filter.
     *
     * @param key the key.
     * @param value the value.
     * @return Boolean where {@code true} means that the item was added and {@code false} means that there's a probability that
     *         the item was already added to the filter or the filter is full.
     */
    Flux<Boolean> bfInsert(K key, V value);

    /**
     * Add an item to the Bloom Filter.
     *
     * @param key the key.
     * @param insertArgs the insert arguments.
     * @param value the value.
     * @return Boolean where {@code true} means that the item was added and {@code false} means that there's a probability that
     *         the item was already added to the filter or the filter is full.
     */
    Flux<Boolean> bfInsert(K key, BfInsertArgs insertArgs, V value);

    /**
     * Add one or more items to the Bloom Filter.
     *
     * @param key the key.
     * @param values the values.
     * @return Boolean where {@code true} means that the item was added and {@code false} means that there's a probability that
     *         the item was already added to the filter or the filter is full.
     */
    Flux<Boolean> bfInsert(K key, V... values);

    /**
     * Add one or more items to the Bloom Filter.
     *
     * @param key the key.
     * @param insertArgs the insert arguments.
     * @param values the values.
     * @return Boolean where {@code true} means that the item was added and {@code false} means that there's a probability that
     *         the item was already added to the filter or the filter is full.
     */
    Flux<Boolean> bfInsert(K key, BfInsertArgs insertArgs, V... values);

    /**
     * Restores a Bloom filter previously saved using BF.SCANDUMP.
     *
     * @param key the key.
     * @param iterator the iterator.
     * @param data the data.
     * @return String simple-string-reply {@code OK} if {@code BF.LOADCHUNK} was executed correctly.
     */
    Mono<String> bfLoadChunk(K key, long iterator, byte[] data);

    /**
     * Add one or more items to the Bloom Filter.
     *
     * @param key the key.
     * @param values the values.
     * @return Boolean of {@code true} or {@code false} where true means that the item was newly added and false means that
     *         there's a probability that the item was already added to the filter.
     */
    Flux<Boolean> bfMAdd(K key, V... values);

    /**
     * Check if one or more items exist in the filter.
     *
     * @param key the key.
     * @param values the values.
     * @return Boolean of {@code true} or {@code false} where true means that, with high probability, the item was already added
     *         to the filter, and false means that key does not exist or that item was definitely not added to the filter.
     */
    Flux<Boolean> bfMExists(K key, V... values);

    /**
     * Creates an empty Bloom filter with a single sub-filter for the initial specified capacity and with an upper bound error
     * rate.
     *
     * @param key the key.
     * @param errorRate the error rate.
     * @param capacity the capacity.
     * @return String simple-string-reply {@code OK} if {@code BF.RESERVE} was executed correctly.
     */
    Mono<String> bfReserve(K key, double errorRate, long capacity);

    /**
     * Creates an empty Bloom filter with a single sub-filter for the initial specified capacity and with an upper bound error
     * rate.
     *
     * @param key the key.
     * @param errorRate the error rate.
     * @param capacity the capacity.
     * @param reserveArgs the reserve arguments.
     * @return String simple-string-reply {@code OK} if {@code BF.RESERVE} was executed correctly.
     */
    Mono<String> bfReserve(K key, double errorRate, long capacity, BfReserveArgs reserveArgs);

    /**
     * Begins an incremental save of the Bloom filter.
     *
     * @param key the key.
     * @param iterator the iterator.
     * @return BfScanDumpValue the scan dump value.
     */
    Mono<BfScanDumpValue> bfScanDump(K key, long iterator);

}
