# Note: this action is used as a part of redis oss release and test automation in
# redis-developer/redis-oss-release-automation repo
name: 'Run Lettuce Tests'
description: 'Run Lettuce tests in a containerized environment'

inputs:
  redis_version:
    description: 'Redis version to test against'
    required: false
  client_libs_test_image_tag:
    description: 'Custom client libs test image tag to use instead of redis_version'
    required: false
    default: ''
  client_libs_test_image:
    description: 'Custom client libs test image name to use'
    required: false
    default: ''
  java_version:
    description: 'Java version to use'
    required: false
    default: '8'
  java_distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  codecov_token:
    description: 'Codecov token for uploading coverage'
    required: false
    default: ''
  # repository and ref are required for correct checkout when using action
  # externally (e.g.: in redis-developer/redis-oss-release-automation)
  repository:
    description: 'Git repository to checkout'
    required: false
    default: ''
  ref:
    description: 'Git ref to checkout'
    required: false
    default: ''
  redis_env_work_dir:
    description: 'Redis env work directory'
    required: false
    default: ''
  redis_env_conf_dir:
    description: 'Redis env conf directory'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}

    - name: Validate inputs and prepare environment
      shell: bash
      id: args
      env:
        REDIS_VERSION: ${{ inputs.redis_version }}
        CLIENT_LIBS_TEST_IMAGE: ${{ inputs.client_libs_test_image }}
        CLIENT_LIBS_TEST_IMAGE_TAG: ${{ inputs.client_libs_test_image_tag }}
        REDIS_ENV_WORK_DIR: ${{ inputs.redis_env_work_dir }}
        REDIS_ENV_CONF_DIR: ${{ inputs.redis_env_conf_dir }}
        REDIS_VERSION_LABEL: ${{ inputs.client_libs_test_image_tag || inputs.redis_version }}
      run: |
        echo "::group::Validate inputs"
        make_args=()

        if [ -n "$CLIENT_LIBS_TEST_IMAGE" ]; then
          make_args+=(CLIENT_LIBS_TEST_IMAGE="$CLIENT_LIBS_TEST_IMAGE")
        fi

        if [ -n "$CLIENT_LIBS_TEST_IMAGE_TAG" ]; then
          make_args+=(CLIENT_LIBS_TEST_IMAGE_TAG="$CLIENT_LIBS_TEST_IMAGE_TAG")
        elif [ -n "$REDIS_VERSION" ]; then
          make_args+=(version="$REDIS_VERSION")
        else
          echo "Error: redis_version or client_libs_test_image_tag input is required"
          exit 1
        fi

        echo "make_args=${make_args[*]}" | tee -a ${GITHUB_OUTPUT}
        echo "redis_version_label=$REDIS_VERSION_LABEL" | tee -a ${GITHUB_OUTPUT}
        echo "::endgroup::"

        echo "::group::Prepare environment paths"
        if [ -z "$REDIS_ENV_CONF_DIR" ]; then
          REDIS_ENV_CONF_DIR=$(readlink -f "${{ github.action_path }}/../../../src/test/resources/docker-env")
        fi
        echo "redis_env_conf_dir=$REDIS_ENV_CONF_DIR" | tee -a ${GITHUB_OUTPUT}

        if [ -n "$REDIS_ENV_WORK_DIR" ]; then
          echo "redis_env_work_dir=$REDIS_ENV_WORK_DIR" | tee -a ${GITHUB_OUTPUT}
        else
          REDIS_ENV_WORK_DIR=$(mktemp -du)
          echo "redis_env_work_dir=$REDIS_ENV_WORK_DIR" | tee -a ${GITHUB_OUTPUT}
        fi
        echo "::endgroup::"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java_version }}
        distribution: ${{ inputs.java_distribution }}
        cache: 'maven'

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.19.0
      with:
        # we already checked out the code and
        # checkout without params breaks external usage of the run-tests action
        checkout-enabled: false
        java-version: ${{ inputs.java_version }}

    - name: Set up Docker Compose environment
      shell: bash
      run: |
        echo "::group::Create work directory"
        mkdir -m 777 $REDIS_ENV_WORK_DIR
        echo "Work directory: $REDIS_ENV_WORK_DIR"
        echo "::endgroup::"

        echo "::group::Start Redis containers"
        make start ${{ steps.args.outputs.make_args }}
        echo "::endgroup::"
      env:
        REDIS_ENV_CONF_DIR: ${{ steps.args.outputs.redis_env_conf_dir }}
        REDIS_ENV_WORK_DIR: ${{ steps.args.outputs.redis_env_work_dir }}

    - name: Maven offline
      shell: bash
      run: |
        echo "::group::Download Maven dependencies"
        mvn -q dependency:go-offline
        echo "::endgroup::"
      continue-on-error: true

    - name: Run tests
      shell: bash
      run: |
        echo "::group::Run test suite"
        export TEST_WORK_FOLDER=$REDIS_ENV_WORK_DIR
        make test-coverage
        echo "::endgroup::"
      env:
        REDIS_ENV_WORK_DIR: ${{ steps.args.outputs.redis_env_work_dir }}
        JVM_OPTS: -Xmx3200m
        TERM: dumb

    - name: Tear down Docker Compose environment
      if: always()
      shell: bash
      run: |
        echo "::group::Stop Redis containers"
        make stop
        echo "::endgroup::"
      continue-on-error: true

    - name: Upload coverage reports to Codecov
      if: inputs.codecov_token != ''
      uses: codecov/codecov-action@v4
      with:
        token: ${{ inputs.codecov_token }}

    - name: Upload test failure reports to Codecov
      if: always() && inputs.codecov_token != ''
      uses: codecov/test-results-action@v1
      with:
        fail_ci_if_error: false
        files: ./target/surefire-reports/TEST*,./target/failsafe-reports/TEST*
        verbose: ${{ runner.debug }}
        token: ${{ inputs.codecov_token }}
